const VOCABULARY = [

{ en: "to shake", past: "shook", he: "לנער" },
{ en: "to shoot", past: "shot", he: "לירות" },
{ en: "to shine", past: "shone", he: "לזרוח" },
{ en: "to shut", past: "shut", he: "לסגור" },
{ en: "to sing", past: "sang", he: "לשיר" },
{ en: "to sit", past: "sat", he: "לשבת" },
{ en: "to sleep", past: "slept", he: "לישון" },
{ en: "to speak", past: "spoke", he: "לדבר" },
{ en: "to spend", past: "spent", he: "לבזבז" },
{ en: "to stand", past: "stood", he: "לעמוד" },
{ en: "to steal", past: "stole", he: "לגנוב" },
{ en: "to sweep", past: "swept", he: "לטאטא" },
{ en: "to swim", past: "swam", he: "לשחות" },
{ en: "to take", past: "took", he: "לקחת" },
{ en: "to teach", past: "taught", he: "ללמד" },
{ en: "to tear", past: "tore", he: "לקרוע" },
{ en: "to tell", past: "told", he: "לאמר" },
{ en: "to think", past: "thought", he: "לחשוב" },
{ en: "to throw", past: "threw", he: "לזרוק" },
{ en: "to understand", past: "understood", he: "להבין" },
{ en: "to wake", past: "woke", he: "להתעורר" },
{ en: "to wear", past: "wore", he: "ללבוש" },
{ en: "to win", past: "won", he: "לנצח" },
{ en: "to write", past: "wrote", he: "לכתוב" },

];
