const VOCABULARY = [

{ en: "to be", past: "was/were", he: "להיות" },
{ en: "to beat", past: "beat", he: "להביס" },
{ en: "to become", past: "became", he: "להפוך להיות" },
{ en: "to begin", past: "began", he: "להתחיל" },
{ en: "to bite", past: "bit", he: "לנשוך" },
{ en: "to blow", past: "blew", he: "לנשוף" },
{ en: "to break", past: "broke", he: "לשבור" },
{ en: "to bring", past: "brought", he: "להביא" },
{ en: "to build", past: "built", he: "לבנות" },
{ en: "to buy", past: "bought", he: "לקנות" },
{ en: "to catch", past: "caught", he: "לתפוס" },
{ en: "to choose", past: "chose", he: "לבחור" },
{ en: "to come", past: "came", he: "לבוא" },
{ en: "to cost", past: "cost", he: "עולה" },
{ en: "to cut", past: "cut", he: "לגזור" },
{ en: "to dig", past: "dug", he: "לחפור" },
{ en: "to do", past: "did", he: "לעשות" },
{ en: "to draw", past: "drew", he: "לצייר" },
{ en: "to dream", past: "dreamt/dreamed", he: "לחלום" },
{ en: "to drink", past: "drank", he: "לשתות" },
{ en: "to drive", past: "drove", he: "לנהוג" },
{ en: "to eat", past: "ate", he: "לאכול" },
{ en: "to fall", past: "fell", he: "ליפול" },

];
